language: cpp
os: windows
env:
  - MSBUILD_PATH="C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin"
install:
  - choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"
script:
    - cmake -G "Visual Studio 15 2017 Win64"
    - dotnet restore ./GBHttpServerFramework.sln
    - cmake --build .
